apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-04-01T13:28:04Z"
  generation: 2
  labels:
    app: orderservice
  name: orderservice
  namespace: default
  resourceVersion: "3499"
  selfLink: /apis/apps/v1/namespaces/default/deployments/orderservice
  uid: 9ded11a2-741c-11ea-8333-42010a80001a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: orderservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orderservice
    spec:
      containers:
      - image: anuj1508/nagp_orderservice:tag1
        imagePullPolicy: IfNotPresent
        name: nagp-orderservice-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-01T13:28:15Z"
    lastUpdateTime: "2020-04-01T13:28:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-01T13:28:04Z"
    lastUpdateTime: "2020-04-01T13:28:15Z"
    message: ReplicaSet "orderservice-6f4fd8f9bc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
