apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-04-01T13:23:18Z"
  generation: 2
  labels:
    app: userservice
  name: userservice
  namespace: default
  resourceVersion: "2460"
  selfLink: /apis/apps/v1/namespaces/default/deployments/userservice
  uid: f3210be6-741b-11ea-8333-42010a80001a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: userservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: userservice
    spec:
      containers:
      - image: anuj1508/nagp_userservice:tag1
        imagePullPolicy: IfNotPresent
        name: nagp-userservice-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-01T13:23:29Z"
    lastUpdateTime: "2020-04-01T13:23:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-01T13:23:18Z"
    lastUpdateTime: "2020-04-01T13:23:29Z"
    message: ReplicaSet "userservice-74d94dc544" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
